method: oflow
data:
  input_type: img_seq
model:
  encoder_temporal: conv_3D
  encoder: resnet18
  decoder_kwargs:
    hidden_size: 256
    legacy: true
  c_dim: 256
training:
  out_dir: out/img/oflow
